In [7]:
import pandas as pd

df = pd.read_csv("data/data.csv")

#examining the columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134639 entries, 0 to 134638
Data columns (total 36 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   CMPLNT_NUM                134639 non-null  object
 1   ADDR_PCT_CD               134639 non-null  int64
 2   BORO_NM                   134639 non-null  object
 3   CMPLNT_FR_DT              134639 non-null  object
 4   CMPLNT_FR_TM              134639 non-null  object
 5   CMPLNT_TO_DT              127696 non-null  object
 6   CMPLNT_TO_TM              134639 non-null  object
 7   CRM_ATPT_CPTD_CD          134639 non-null  object
 8   HADEVELOPT                134639 non-null  object
 9   HOUSING_PSA               8559 non-null    float64
 10  JURISDICTION_CODE         134639 non-null  int64
 11  JURIS_DESC                134639 non-null  object
 12  KY_CD                     134639 non-null  int64
 13  LAW_CAT_CD                134639 non-null  object
 14  LOC_OF_OCCUR_DESC         134639 non-null  object
 15  OFNS_DESC                 134639 non-null  object
 16  PARKS_NM                  134639 non-null  object
 17  PATROL_BORO               134639 non-null  object
 18  PD_CD                     134569 non-null  float64
 19  PD_DESC                   134639 non-null  object
 20  PREM_TYP_DESC             134639 non-null  object
 21  RPT_DT                    134639 non-null  object
 22  STATION_NAME              134639 non-null  object
 23  SUSP_AGE_GROUP            134639 non-null  object
 24  SUSP_RACE                 134639 non-null  object
 25  SUSP_SEX                  134639 non-null  object
 26  TRANSIT_DISTRICT          5831 non-null    float64
 27  VIC_AGE_GROUP             134639 non-null  object
 28  VIC_RACE                  134639 non-null  object
 29  VIC_SEX                   134639 non-null  object
 30  X_COORD_CD                134637 non-null  float64
 31  Y_COORD_CD                134637 non-null  float64
 32  Latitude                  134637 non-null  float64
 33  Longitude                 134637 non-null  float64
 34  Lat_Lon                   134637 non-null  object
 35  New Georeferenced Column  134637 non-null  object
dtypes: float64(7), int64(3), object(26)
memory usage: 37.0+ MB

In [27]:
#reviweing types of recorded offenses
print(df['OFNS_DESC'].unique())

['CRIMINAL MISCHIEF & RELATED OF' 'GRAND LARCENY OF MOTOR VEHICLE'
 'HARRASSMENT 2' 'FRAUDS' 'SEX CRIMES' 'PETIT LARCENY' 'BURGLARY'
 'VEHICLE AND TRAFFIC LAWS' 'FELONY ASSAULT' 'DANGEROUS DRUGS'
 'GRAND LARCENY' 'OFFENSES AGAINST PUBLIC ADMINI'
 'MURDER & NON-NEGL. MANSLAUGHTER' 'ROBBERY'
 'INTOXICATED & IMPAIRED DRIVING' 'MISCELLANEOUS PENAL LAW'
 'OFF. AGNST PUB ORD SENSBLTY &' 'DANGEROUS WEAPONS' 'FORGERY' 'RAPE'
 'NYS LAWS-UNCLASSIFIED FELONY' 'OTHER STATE LAWS (NON PENAL LA'
 'CRIMINAL TRESPASS' 'ASSAULT 3 & RELATED OFFENSES' 'ADMINISTRATIVE CODE'
 'UNAUTHORIZED USE OF A VEHICLE' 'ARSON' 'OFFENSES INVOLVING FRAUD'
 'OFFENSES AGAINST THE PERSON' 'THEFT-FRAUD'
 'AGRICULTURE & MRKTS LAW-UNCLASSIFIED' 'OTHER OFFENSES RELATED TO THEF'
 'POSSESSION OF STOLEN PROPERTY' 'CANNABIS RELATED OFFENSES' 'GAMBLING'
 'KIDNAPPING & RELATED OFFENSES' "BURGLAR'S TOOLS"
 'ALCOHOLIC BEVERAGE CONTROL LAW' 'PETIT LARCENY OF MOTOR VEHICLE'
 'ANTICIPATORY OFFENSES' 'ESCAPE 3' 'THEFT OF SERVICES' 'KIDNAPPING'
 'OTHER STATE LAWS' 'FRAUDULENT ACCOSTING'
 'PROSTITUTION & RELATED OFFENSES' 'INTOXICATED/IMPAIRED DRIVING'
 'OFFENSES AGAINST PUBLIC SAFETY' 'DISORDERLY CONDUCT'
 'ENDAN WELFARE INCOMP' 'CHILD ABANDONMENT/NON SUPPORT'
 'UNLAWFUL POSS. WEAP. ON SCHOOL' 'OFFENSES RELATED TO CHILDREN'
 'JOSTLING' 'FORTUNE TELLING' 'HOMICIDE-NEGLIGENT,UNCLASSIFIE' '(null)'
 'DISRUPTION OF A RELIGIOUS SERV' 'NYS LAWS-UNCLASSIFIED VIOLATION'
 'FELONY SEX CRIMES']

In [29]:
#subsetting the rows for disorderly conduct crimes & sorting based on location type ("PREM_TYP_DESC")

disorderly_conduct_crimes = df[df['OFNS_DESC'] == 'DISORDERLY CONDUCT']
disorderly_conduct_crimes = disorderly_conduct_crimes.sort_values("PREM_TYP_DESC")

print(disorderly_conduct_crimes['PREM_TYP_DESC'].unique())

#change pandas settings to display all columns
pd.set_option('display.max_columns', None)

disorderly_conduct_crimes

['(null)' 'AIRPORT TERMINAL' 'BRIDGE' 'CLOTHING/BOUTIQUE'
 'COMMERCIAL BUILDING' 'DEPARTMENT STORE' 'OTHER' 'PARK/PLAYGROUND'
 'RESIDENCE - PUBLIC HOUSING' 'RESIDENCE-HOUSE' 'STREET'
 'TRANSIT - NYC SUBWAY' 'TRANSIT FACILITY (OTHER)']

,CMPLNT_NUM,ADDR_PCT_CD,BORO_NM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,CRM_ATPT_CPTD_CD,HADEVELOPT,HOUSING_PSA,JURISDICTION_CODE,JURIS_DESC,KY_CD,LAW_CAT_CD,LOC_OF_OCCUR_DESC,OFNS_DESC,PARKS_NM,PATROL_BORO,PD_CD,PD_DESC,PREM_TYP_DESC,RPT_DT,STATION_NAME,SUSP_AGE_GROUP,SUSP_RACE,SUSP_SEX,TRANSIT_DISTRICT,VIC_AGE_GROUP,VIC_RACE,VIC_SEX,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,New Georeferenced Column
53292,281711675,103,QUEENS,02/05/2024,20:55:00,02/05/2024,21:01:00,COMPLETED,(null),NaN,0,N.Y. POLICE DEPT,572,VIOLATION,(null),DISORDERLY CONDUCT,(null),PATROL BORO QUEENS SOUTH,625.0,DISORDERLY CONDUCT,(null),02/05/2024,(null),45-64,BLACK,M,NaN,25-44,UNKNOWN,L,1039647.0,195586.0,40.703342,-73.800203,"(40.70334171028012, -73.80020318978802)",POINT (-73.80020318978802 40.70334171028012)
10552,280146077,5,MANHATTAN,01/08/2024,10:25:00,01/08/2024,10:29:00,COMPLETED,(null),NaN,0,N.Y. POLICE DEPT,572,VIOLATION,(null),DISORDERLY CONDUCT,(null),PATROL BORO MAN SOUTH,625.0,DISORDERLY CONDUCT,(null),01/08/2024,(null),25-44,UNKNOWN,F,NaN,UNKNOWN,UNKNOWN,E,984990.0,200136.0,40.716012,-73.997332,"(40.7160120119955, -73.9973320301008)",POINT (-73.9973320301008 40.7160120119955)
10424,280146074,5,MANHATTAN,01/08/2024,10:25:00,01/08/2024,10:29:00,COMPLETED,(null),NaN,0,N.Y. POLICE DEPT,572,VIOLATION,(null),DISORDERLY CONDUCT,(null),PATROL BORO MAN SOUTH,625.0,DISORDERLY CONDUCT,(null),01/08/2024,(null),65+,WHITE,F,NaN,UNKNOWN,UNKNOWN,E,983125.0,198608.0,40.711810,-74.004058,"(40.711809718636395, -74.00405797735951)",POINT (-74.00405797735951 40.711809718636395)
10426,280146064,5,MANHATTAN,01/08/2024,10:00:00,01/08/2024,10:19:00,COMPLETED,(null),NaN,0,N.Y. POLICE DEPT,572,VIOLATION,(null),DISORDERLY CONDUCT,(null),PATROL BORO MAN SOUTH,625.0,DISORDERLY CONDUCT,(null),01/08/2024,(null),45-64,WHITE,F,NaN,UNKNOWN,UNKNOWN,E,983125.0,198608.0,40.711810,-74.004058,"(40.711809718636395, -74.00405797735951)",POINT (-74.00405797735951 40.711809718636395)
10533,280154777,5,MANHATTAN,01/08/2024,01:30:00,01/08/2024,10:50:00,COMPLETED,(null),NaN,0,N.Y. POLICE DEPT,572,VIOLATION,(null),DISORDERLY CONDUCT,(null),PATROL BORO MAN SOUTH,625.0,DISORDERLY CONDUCT,(null),01/08/2024,(null),25-44,WHITE,M,NaN,UNKNOWN,UNKNOWN,E,985461.0,199940.0,40.715466,-73.995632,"(40.71546572952549, -73.99563157321111)",POINT (-73.99563157321111 40.71546572952549)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83584,282817879,79,BROOKLYN,02/26/2024,18:00:00,02/26/2024,18:06:00,COMPLETED,(null),NaN,1,N.Y. TRANSIT POLICE,572,VIOLATION,(null),DISORDERLY CONDUCT,(null),PATROL BORO BKLYN NORTH,625.0,DISORDERLY CONDUCT,TRANSIT - NYC SUBWAY,02/26/2024,FRANKLIN AVENUE,45-64,BLACK,M,30.0,UNKNOWN,UNKNOWN,E,996546.0,187436.0,40.681137,-73.955668,"(40.6811367070632, -73.9556676077586)",POINT (-73.9556676077586 40.6811367070632)
92834,283139969,40,BRONX,03/03/2024,23:41:00,03/03/2024,23:50:00,COMPLETED,(null),NaN,1,N.Y. TRANSIT POLICE,572,VIOLATION,(null),DISORDERLY CONDUCT,(null),PATROL BORO BRONX,625.0,DISORDERLY CONDUCT,TRANSIT - NYC SUBWAY,03/03/2024,3 AVENUE-149 STREET,25-44,WHITE HISPANIC,M,12.0,18-24,BLACK,F,1007046.0,236603.0,40.816067,-73.917644,"(40.81606683945181, -73.91764392674679)",POINT (-73.91764392674679 40.81606683945181)
104268,283538964,77,BROOKLYN,03/11/2024,12:15:00,03/11/2024,12:21:00,COMPLETED,(null),NaN,1,N.Y. TRANSIT POLICE,572,VIOLATION,(null),DISORDERLY CONDUCT,(null),PATROL BORO BKLYN NORTH,625.0,DISORDERLY CONDUCT,TRANSIT - NYC SUBWAY,03/11/2024,FRANKLIN AVENUE,25-44,BLACK,M,32.0,UNKNOWN,UNKNOWN,E,995908.0,183618.0,40.670658,-73.957974,"(40.67065802222989, -73.95797447716627)",POINT (-73.95797447716627 40.67065802222989)
7856,280072685,14,MANHATTAN,01/06/2024,15:35:00,01/06/2024,15:50:00,COMPLETED,(null),NaN,1,N.Y. TRANSIT POLICE,572,VIOLATION,(null),DISORDERLY CONDUCT,(null),PATROL BORO MAN SOUTH,625.0,DISORDERLY CONDUCT,TRANSIT - NYC SUBWAY,01/06/2024,42 ST.-TIMES SQUARE,(null),(null),(null),1.0,UNKNOWN,UNKNOWN,D,985764.0,213806.0,40.753533,-73.994537,"(40.7535327012632, -73.9945368920152)",POINT (-73.9945368920152 40.7535327012632)
121112,284196673,14,MANHATTAN,03/22/2024,22:25:00,NaN,(null),COMPLETED,(null),NaN,17,MTA POLICE DEPT,572,VIOLATION,INSIDE,DISORDERLY CONDUCT,(null),PATROL BORO MAN SOUTH,625.0,DISORDERLY CONDUCT,TRANSIT FACILITY (OTHER),03/22/2024,(null),25-44,BLACK,M,NaN,UNKNOWN,UNKNOWN,L,986526.0,212304.0,40.749404,-73.991784,"(40.749404, -73.991784)",POINT (-73.991784 40.749404)