In [8]:
import pandas as pd
df = pd.read_csv('data/data.csv')

In [10]:
df['CMPLNT_NUM']

0     286159230
1     284390764
2     282326671
3     281045110
4     282616059
5     283299802
6     285354060
7     283173106
8     285539608
9     281731995
10    284167496
Name: CMPLNT_NUM, dtype: int64

In [12]:
df.head()

,CMPLNT_NUM,ADDR_PCT_CD,BORO_NM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,CRM_ATPT_CPTD_CD,HADEVELOPT,JURIS_DESC,...,PARKS_NM,PD_CD,PD_DESC,PREM_TYP_DESC,RPT_DT,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon
0,286159230,24,MANHATTAN,01/01/2016,15:00:00,01/01/2018,23:00:00,COMPLETED,(null),N.Y. HOUSING POLICE,...,(null),168,SODOMY 1,RESIDENCE - PUBLIC HOUSING,05/01/2024,993369,229307,40.796074,-73.967067,"(40.7960743128304, -73.9670667458109)"
1,284390764,13,MANHATTAN,01/01/2016,12:00:00,03/26/2024,12:00:00,COMPLETED,(null),N.Y. POLICE DEPT,...,(null),638,"HARASSMENT,SUBD 3,4,5",RESIDENCE - APT. HOUSE,03/26/2024,989439,206297,40.732914,-73.981276,"(40.732914, -73.981276)"
2,282326671,28,MANHATTAN,01/10/2016,12:00:00,01/10/2016,12:00:00,COMPLETED,(null),N.Y. POLICE DEPT,...,(null),349,"LARCENY,PETIT OF LICENSE PLATE",OTHER,02/16/2024,1002583,229363,40.796206,-73.933787,"(40.796206, -73.933787)"
3,281045110,23,MANHATTAN,01/25/2016,00:01:00,NaN,(null),COMPLETED,(null),N.Y. HOUSING POLICE,...,(null),847,"NY STATE LAWS,UNCLASSIFIED FEL",RESIDENCE - PUBLIC HOUSING,01/24/2024,998746,230395,40.799045,-73.947642,"(40.799045, -73.947642)"
4,282616059,5,MANHATTAN,05/11/2016,09:30:00,05/11/2016,10:00:00,COMPLETED,(null),N.Y. POLICE DEPT,...,(null),764,BAIL JUMPING 1 & 2,OTHER,02/22/2024,983903,200257,40.716337,-74.001251,"(40.716337, -74.001251)"